user root;
worker_processes auto;
events {
    worker_connections 1024;
}
rtmp {
    server {
        listen 19350;
        chunk_size 4096;
        application a01 {
            live on;
            dash on;
            dash_path web/a01;
        }
        application a02 {
            live on;
            dash on;
            dash_path web/a02;
        }
        application a03 {
            live on;
            dash on;
            dash_path web/a03;
        }
    }
}
http {
    sendfile off;
    tcp_nopush on;
    directio 512;
    include mime.types;
    default_type application/octet-stream;
    server {
        listen 80;
        server_name localhost;
        location / {
            add_header 'Cache-Control' 'no-cache';
            root web;
        }
    }
    server {
        listen 443 ssl;
        server_name localhost;
        ssl_certificate fullchain.pem;
        ssl_certificate_key privkey.pem;
        location / {
            client_max_body_size 0;
            chunked_transfer_encoding on;
            proxy_http_version 1.1;
            proxy_pass http://127.0.0.1:8000/;
            proxy_pass_request_headers on;
            proxy_buffering off;
            proxy_request_buffering off;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            add_header 'Cache-Control' 'no-cache';
            root web;
        }
    }
    server {
        listen 99 ssl;
        server_name localhost;
        ssl_certificate fullchain.pem;
        ssl_certificate_key privkey.pem;
        location /a01 {
            types {
                application/dash+xml mpd;
                video/mp4 mp4;
            }
            add_header Cache-Control no-cache;
            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'Access-Control-Expose-Headers' 'Content-Length';
            root web;
        }
        location /a02 {
            types {
                application/dash+xml mpd;
                video/mp4 mp4;
            }
            add_header Cache-Control no-cache;
            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'Access-Control-Expose-Headers' 'Content-Length';
            root web;
        }
        location /a03 {
            types {
                application/dash+xml mpd;
                video/mp4 mp4;
            }
            add_header Cache-Control no-cache;
            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'Access-Control-Expose-Headers' 'Content-Length';
            root web;
        }
    }
}
